extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
  jest: true
rules:
  "react/prop-types": off
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"
  import/no-unresolved:
    - 0
